# Generated by Django 3.2.5 on 2021-07-07 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('list_price', models.FloatField()),
                ('description', models.TextField(max_length=300)),
                ('photo', models.ImageField(upload_to='products')),
            ],
        ),
    ]
